"""empty message

Revision ID: 11f4b6c4f84d
Revises: ad4e3ba9b470
Create Date: 2020-08-24 15:27:21.879614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f4b6c4f84d'
down_revision = 'ad4e3ba9b470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('s_un', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwords', 's_un')
    # ### end Alembic commands ###
